sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

script: mvn clean install -B

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export CONFIG=proshik/config-server

# CONFIG
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $CONFIG:$COMMIT .
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

notifications:
  email:
    - proxoraleksandrovich@gmail.com
